env:
  TZ: Asia/Jakarta
  CCACHE: true
  CCACHE_DIR: /tmp/ccache
  CCACHE_MAXSIZE: 10G
  CCACHE_COMPRESS: true
  TG_TOKEN: ENCRYPTED[d9185ab32fea60b59b9caac7865c156001691d0c6c87c825c32a3db288ed566a8ac07cfe7ff445fb2c0e61f57c06b486]
  TG_CHAT_ID: ENCRYPTED[d1175d4be5c2ebcb2ce25c91ec7c71abeb738d22d563c4fc0afdb9f528c2d6997b98e29309468198038eb159cc709e91]
  

task:
  name: "Kernel Build"
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:r-ubuntu
    cpu: 8
    memory: 32G

  # Cache configuration
  ccache_cache:
    folder: /cirrus/ccache
    fingerprint_script:
      - echo "v1"
    populate_script:
      - mkdir -p /cirrus/ccache

  setup_script:
    - apt-get update
    - apt-get install -y sudo curl wget git jq figlet aria2 python3-all-dev apt-utils
    - apt-get install -y libtinfo6 libncurses6 libncurses-dev libncurses5-dev lsb-release lsb-base ccache
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen && /usr/sbin/locale-gen
    - ln -snf /usr/share/zoneinfo/"$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
    - mkdir -p /cirrus/ccache
    - ccache -M 20G
    - ccache -o compression=true
    - ccache -o compression_level=6
    - apt-get update

  build_environment_script:
    - git clone https://github.com/akhilnarang/scripts.git -b master .sc
    - sudo bash .sc/setup/android_build_env.sh

  sync_script:
    - ./sync.sh

  build_script:
    - ./building.sh
